[project]
name = "projeto-streamlit"
version = "0.1.0"
description = ""
authors = [
    {name = "Tiago Cavalca",email = "t.cavalca47@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit (>=1.42.2,<2.0.0)",
    "pandas (>=2.2.3,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
